name: CI
on:
  push:
    branches:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Build
        run: |
          docker build -t phpinfo:latest .
      - name: Docker Run
        run: |
          docker run --name phpinfo -d -p 8080:8080 phpinfo:latest
      - name: Test Application
        run: |
          sleep 10
          curl -s http://localhost:8080 | grep "PHP Version"
